"""update user table

Revision ID: 839e8eb8e371
Revises: e77458b32c54
Create Date: 2022-08-08 10:40:55.667685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839e8eb8e371'
down_revision = 'e77458b32c54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
